# Generated by Django 4.0.1 on 2022-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_interview', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(choices=[('Java Developer', 'Java Developer'), ('Python Delveloper', 'Python Delveloper'), ('UI/UX Developer', 'UI/UX Developer'), ('.NET Developer', '.NET Developer'), ('iOS Developer', 'iOS Developer')], default=None, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('overall_performance', models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100)),
                ('programming_fundamentals', models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100)),
                ('oops_concepts', models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100)),
                ('framework_concepts', models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100)),
                ('restful_concepts', models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100)),
                ('databases', models.CharField(choices=[('5- Exceptional', '5- Exceptional'), ('4- Above Average', '4- Above Average'), ('3- Average', '3- Average'), ('2- Satisfactory', '2- Satisfactory'), ('1- Unsatisfactory', '1- Unsatisfactory')], default=None, max_length=100)),
            ],
        ),
    ]
